import { DiagramContent, DiagramNode } from '../../types/diagram';

export class MongoExporter {
    static generate(diagram: DiagramContent): string {
        const collections = diagram.nodes.filter(n => n.type === 'mongoCollection');
        if (collections.length === 0) return '// No MongoDB collections found in diagram';

        let script = `/**\n * Generated by Moon Modeler\n * Database: MongoDB\n */\n\n`;

        collections.forEach(col => {
            script += this.createCollectionScript(col);
        });

        script += '\n// Indexes\n';
        collections.forEach(col => {
            const colName = col.data.label || 'untitled';
            col.data.fields.forEach(field => {
                if (field.isUnique) {
                    script += `db.${colName}.createIndex({ "${field.name}": 1 }, { unique: true });\n`;
                }
            });
        });

        return script;
    }

    private static createCollectionScript(node: DiagramNode): string {
        const colName = node.data.label || 'untitled_collection';
        const requiredFields: string[] = [];
        const properties: Record<string, any> = {};

        node.data.fields.forEach(field => {
            // Map types
            const bsonType = this.mapType(field.type);
            properties[field.name] = { bsonType };

            if (field.name === '_id') {
                // _id is implicit, but validator supports it
            }

            // Using !isNullable as required
            if (!field.isNullable && field.name !== '_id') {
                requiredFields.push(field.name);
            }
        });

        const validator = {
            $jsonSchema: {
                bsonType: 'object',
                required: requiredFields.length > 0 ? requiredFields : undefined,
                properties,
                additionalProperties: false
            }
        };

        // Formatting JSON
        const jsonString = JSON.stringify({ validator }, null, 2);

        return `db.createCollection("${colName}", ${jsonString});\n\n`;
    }

    private static mapType(uiType: string): string {
        // Simple mapping
        const lower = uiType.toLowerCase();
        if (lower.includes('int') || lower === 'number') return 'number'; // 'int' or 'double' valid too
        if (lower === 'boolean') return 'bool';
        if (lower === 'date') return 'date';
        if (lower === 'objectid') return 'objectId';
        if (lower === 'array') return 'array';
        if (lower === 'object') return 'object';
        return 'string'; // Default
    }
}
